spring.datasource.url=jdbc:postgresql://localhost:5432/beneficios_db
spring.datasource.username=postgres
spring.datasource.password=r31jesus
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true